/**
 * GENERATED by scripts/generate-registry-data.mjs from the extraction
 * fixture at src/theme-core/__fixtures__/scss-defaults.json — then
 * REVIEWED and committed as the maintained, shipped source of truth
 * (design: docs/design/0.6-theme-core.md, "Variable registry").
 *
 * Do not hand-edit values casually: regenerate (extract-scss-defaults.mjs
 * first, then this generator) on a survey-core version-band bump and
 * re-review the diff. This module must NEVER import the JSON fixture —
 * the fixture is the TEST-ONLY oracle and
 * __tests__/registry-vs-fixture.test.ts exhaustively compares the two
 * independent artifacts.
 *
 * Entry semantics:
 *  - `default: null` = the variable is consumed by default-theme SCSS but
 *    never given a fallback or declaration anywhere (e.g.
 *    --sjs-default-font-family — an optional runtime hook; unset in the
 *    pure cascade, so dependent font-family chains resolve to inherit).
 *  - `accentDefault` = the accent-header-context chain for the three
 *    context-dependent header colors (header.scss:6,10,164-199).
 *  - `alternates` = distinct per-consumer fallback expressions found at
 *    OTHER use sites (codex review major 4) — exposed for 0.7 recipes;
 *    non-web-only names with alternates carry an entry in
 *    MULTI_DEFAULT_JUSTIFICATIONS.
 */
import type { RegistryDataEntry } from './registry';

export const REGISTRY_DATA: readonly RegistryDataEntry[] = [
  {
    name: '--background',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#fff',
    source: 'derived:--sjs-questionpanel-backcolor:17',
  },
  {
    name: '--background-dim',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#f3f3f3',
    source: 'derived:--sjs-general-backcolor-dim:23',
  },
  {
    name: '--background-dim-light',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#f9f9f9',
    source: 'derived:--sjs-editorpanel-backcolor:13',
  },
  {
    name: '--base-unit',
    class: 'legacy-alias',
    grammar: {
      kind: 'length',
    },
    default: '8px',
    source: 'derived:--sjs-base-unit:121',
  },
  {
    name: '--blue-light',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(67, 127, 217, 0.1)',
    source: 'derived:--sjs-special-blue-light:59',
  },
  {
    name: '--border',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#d6d6d6',
    source: 'derived:--sjs-border-default:38',
  },
  {
    name: '--border-inside',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(0, 0, 0, 0.16)',
    source: 'derived:--sjs-border-inside:40',
  },
  {
    name: '--border-light',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#eaeaea',
    source: 'derived:--sjs-border-light:39',
  },
  {
    name: '--font-family',
    class: 'legacy-alias',
    grammar: {
      kind: 'string',
    },
    default: 'var(--sjs-default-font-family)',
    source: 'derived:--sjs-font-family:62',
  },
  {
    name: '--foreground',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#161616',
    source: 'derived:--sjs-general-forecolor:33',
  },
  {
    name: '--foreground-light',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#909090',
    source: 'derived:--sjs-general-forecolor-light:34',
  },
  {
    name: '--green',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#19b394',
    source: 'derived:--sjs-special-green:55',
  },
  {
    name: '--green-light',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(25, 179, 148, 0.1)',
    source: 'derived:--sjs-special-green-light:56',
  },
  {
    name: '--primary',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#19b394',
    source: 'derived:--sjs-primary-backcolor:1',
  },
  {
    name: '--primary-foreground',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#fff',
    source: 'derived:--sjs-primary-forecolor:4',
  },
  {
    name: '--primary-foreground-disabled',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(255, 255, 255, 0.25)',
    source: 'derived:--sjs-primary-forecolor-light:5',
  },
  {
    name: '--primary-light',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(25, 179, 148, 0.1)',
    source: 'derived:--sjs-primary-backcolor-light:2',
  },
  {
    name: '--red',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#e60a3e',
    source: 'derived:--sjs-special-red:49',
  },
  {
    name: '--red-light',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(230, 10, 62, 0.1)',
    source: 'derived:--sjs-special-red-light:50',
  },
  {
    name: '--secondary',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#ff9814',
    source: 'derived:--sjs-secondary-backcolor:7',
  },
  {
    name: '--secondary-light',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(255, 152, 20, 0.25)',
    source: 'derived:--sjs-secondary-backcolor-light:8',
  },
  {
    name: '--sjs-article-font-default-fontSize',
    class: 'semantic-derived',
    grammar: {
      kind: 'length',
    },
    default: 'var(--sjs-font-size, 16px)',
    source: 'mixins.scss:83',
  },
  {
    name: '--sjs-article-font-default-fontStretch',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: [
        'normal',
        'ultra-condensed',
        'extra-condensed',
        'condensed',
        'semi-condensed',
        'semi-expanded',
        'expanded',
        'extra-expanded',
        'ultra-expanded',
      ],
    },
    default: 'normal',
    source: 'mixins.scss:88',
  },
  {
    name: '--sjs-article-font-default-fontStyle',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['normal', 'italic', 'oblique'],
    },
    default: 'normal',
    source: 'mixins.scss:87',
  },
  {
    name: '--sjs-article-font-default-fontWeight',
    class: 'preset-base',
    grammar: {
      kind: 'fontWeight',
    },
    default: '400',
    source: 'mixins.scss:86',
  },
  {
    name: '--sjs-article-font-default-letterSpacing',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '0',
    source: 'mixins.scss:89',
  },
  {
    name: '--sjs-article-font-default-lineHeight',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '28px',
    source: 'mixins.scss:90',
  },
  {
    name: '--sjs-article-font-default-paragraphIndent',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '0px',
    source: 'mixins.scss:91',
  },
  {
    name: '--sjs-article-font-default-textCase',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['none', 'uppercase', 'lowercase', 'capitalize'],
    },
    default: 'none',
    source: 'mixins.scss:92',
  },
  {
    name: '--sjs-article-font-default-textDecoration',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['none', 'underline', 'overline', 'line-through'],
    },
    default: 'none',
    source: 'mixins.scss:84',
  },
  {
    name: '--sjs-article-font-large-fontSize',
    class: 'semantic-derived',
    grammar: {
      kind: 'calc',
    },
    default: 'calc(2 * (var(--sjs-font-size, 16px)))',
    source: 'mixins.scss:57',
  },
  {
    name: '--sjs-article-font-large-fontStretch',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: [
        'normal',
        'ultra-condensed',
        'extra-condensed',
        'condensed',
        'semi-condensed',
        'semi-expanded',
        'expanded',
        'extra-expanded',
        'ultra-expanded',
      ],
    },
    default: 'normal',
    source: 'mixins.scss:62',
  },
  {
    name: '--sjs-article-font-large-fontStyle',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['normal', 'italic', 'oblique'],
    },
    default: 'normal',
    source: 'mixins.scss:61',
  },
  {
    name: '--sjs-article-font-large-fontWeight',
    class: 'preset-base',
    grammar: {
      kind: 'fontWeight',
    },
    default: '700',
    source: 'mixins.scss:60',
  },
  {
    name: '--sjs-article-font-large-letterSpacing',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '0',
    source: 'mixins.scss:63',
  },
  {
    name: '--sjs-article-font-large-lineHeight',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '40px',
    source: 'mixins.scss:64',
  },
  {
    name: '--sjs-article-font-large-paragraphIndent',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '0px',
    source: 'mixins.scss:65',
  },
  {
    name: '--sjs-article-font-large-textCase',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['none', 'uppercase', 'lowercase', 'capitalize'],
    },
    default: 'none',
    source: 'mixins.scss:66',
  },
  {
    name: '--sjs-article-font-large-textDecoration',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['none', 'underline', 'overline', 'line-through'],
    },
    default: 'none',
    source: 'mixins.scss:58',
  },
  {
    name: '--sjs-article-font-medium-fontSize',
    class: 'semantic-derived',
    grammar: {
      kind: 'calc',
    },
    default: 'calc(1.5 * (var(--sjs-font-size, 16px)))',
    source: 'mixins.scss:70',
  },
  {
    name: '--sjs-article-font-medium-fontStretch',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: [
        'normal',
        'ultra-condensed',
        'extra-condensed',
        'condensed',
        'semi-condensed',
        'semi-expanded',
        'expanded',
        'extra-expanded',
        'ultra-expanded',
      ],
    },
    default: 'normal',
    source: 'mixins.scss:75',
  },
  {
    name: '--sjs-article-font-medium-fontStyle',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['normal', 'italic', 'oblique'],
    },
    default: 'normal',
    source: 'mixins.scss:74',
  },
  {
    name: '--sjs-article-font-medium-fontWeight',
    class: 'preset-base',
    grammar: {
      kind: 'fontWeight',
    },
    default: '700',
    source: 'mixins.scss:73',
  },
  {
    name: '--sjs-article-font-medium-letterSpacing',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '0',
    source: 'mixins.scss:76',
  },
  {
    name: '--sjs-article-font-medium-lineHeight',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '32px',
    source: 'mixins.scss:77',
  },
  {
    name: '--sjs-article-font-medium-paragraphIndent',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '0px',
    source: 'mixins.scss:78',
  },
  {
    name: '--sjs-article-font-medium-textCase',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['none', 'uppercase', 'lowercase', 'capitalize'],
    },
    default: 'none',
    source: 'mixins.scss:79',
  },
  {
    name: '--sjs-article-font-medium-textDecoration',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['none', 'underline', 'overline', 'line-through'],
    },
    default: 'none',
    source: 'mixins.scss:71',
  },
  {
    name: '--sjs-article-font-x-large-fontSize',
    class: 'semantic-derived',
    grammar: {
      kind: 'calc',
    },
    default: 'calc(3 * (var(--sjs-font-size, 16px)))',
    source: 'mixins.scss:44',
  },
  {
    name: '--sjs-article-font-x-large-fontStretch',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: [
        'normal',
        'ultra-condensed',
        'extra-condensed',
        'condensed',
        'semi-condensed',
        'semi-expanded',
        'expanded',
        'extra-expanded',
        'ultra-expanded',
      ],
    },
    default: 'normal',
    source: 'mixins.scss:49',
  },
  {
    name: '--sjs-article-font-x-large-fontStyle',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['normal', 'italic', 'oblique'],
    },
    default: 'normal',
    source: 'mixins.scss:48',
  },
  {
    name: '--sjs-article-font-x-large-fontWeight',
    class: 'preset-base',
    grammar: {
      kind: 'fontWeight',
    },
    default: '700',
    source: 'mixins.scss:47',
  },
  {
    name: '--sjs-article-font-x-large-letterSpacing',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '0',
    source: 'mixins.scss:50',
  },
  {
    name: '--sjs-article-font-x-large-lineHeight',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '56px',
    source: 'mixins.scss:51',
  },
  {
    name: '--sjs-article-font-x-large-paragraphIndent',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '0px',
    source: 'mixins.scss:52',
  },
  {
    name: '--sjs-article-font-x-large-textCase',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['none', 'uppercase', 'lowercase', 'capitalize'],
    },
    default: 'none',
    source: 'mixins.scss:53',
  },
  {
    name: '--sjs-article-font-x-large-textDecoration',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['none', 'underline', 'overline', 'line-through'],
    },
    default: 'none',
    source: 'mixins.scss:45',
  },
  {
    name: '--sjs-article-font-xx-large-fontSize',
    class: 'semantic-derived',
    grammar: {
      kind: 'calc',
    },
    default: 'calc(4 * (var(--sjs-font-size, 16px)))',
    source: 'mixins.scss:31',
  },
  {
    name: '--sjs-article-font-xx-large-fontStretch',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: [
        'normal',
        'ultra-condensed',
        'extra-condensed',
        'condensed',
        'semi-condensed',
        'semi-expanded',
        'expanded',
        'extra-expanded',
        'ultra-expanded',
      ],
    },
    default: 'normal',
    source: 'mixins.scss:36',
  },
  {
    name: '--sjs-article-font-xx-large-fontStyle',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['normal', 'italic', 'oblique'],
    },
    default: 'normal',
    source: 'mixins.scss:35',
  },
  {
    name: '--sjs-article-font-xx-large-fontWeight',
    class: 'preset-base',
    grammar: {
      kind: 'fontWeight',
    },
    default: '700',
    source: 'mixins.scss:34',
  },
  {
    name: '--sjs-article-font-xx-large-letterSpacing',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '0',
    source: 'mixins.scss:37',
  },
  {
    name: '--sjs-article-font-xx-large-lineHeight',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '64px',
    source: 'mixins.scss:38',
  },
  {
    name: '--sjs-article-font-xx-large-paragraphIndent',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '0px',
    source: 'mixins.scss:39',
  },
  {
    name: '--sjs-article-font-xx-large-textCase',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['none', 'uppercase', 'lowercase', 'capitalize'],
    },
    default: 'none',
    source: 'mixins.scss:40',
  },
  {
    name: '--sjs-article-font-xx-large-textDecoration',
    class: 'preset-base',
    grammar: {
      kind: 'keyword',
      allowed: ['none', 'underline', 'overline', 'line-through'],
    },
    default: 'none',
    source: 'mixins.scss:32',
  },
  {
    name: '--sjs-base-unit',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: 'var(--base-unit, 8px)',
    source: 'variables.scss:121',
  },
  {
    name: '--sjs-border-25-overlay',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: '#00000026',
    source: 'blocks/sv-scroll.scss:40',
  },
  {
    name: '--sjs-border-default',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--border, #d6d6d6)',
    source: 'variables.scss:38',
    alternates: [
      {
        expression:
          'var(--sjs-border-inside, var(--border-inside, rgba(0, 0, 0, 0.16)))',
        source: 'blocks/sv-ranking.scss:448',
      },
    ],
  },
  {
    name: '--sjs-border-inside',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--border-inside, rgba(0, 0, 0, 0.16))',
    source: 'variables.scss:40',
  },
  {
    name: '--sjs-border-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--border-light, #eaeaea)',
    source: 'variables.scss:39',
  },
  {
    name: '--sjs-collapse-fade-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:141',
  },
  {
    name: '--sjs-collapse-move-out-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:143',
  },
  {
    name: '--sjs-collapse-move-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:142',
  },
  {
    name: '--sjs-corner-radius',
    class: 'preset-base',
    grammar: {
      kind: 'length',
    },
    default: '4px',
    source: 'variables.scss:29',
  },
  {
    name: '--sjs-default-font-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default: null,
    source: 'variables.scss:62',
  },
  {
    name: '--sjs-editor-background',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default:
      'var(--sjs-general-backcolor-dim-light, var(--background-dim-light, #f9f9f9))',
    source: 'variables.scss:13',
  },
  {
    name: '--sjs-editorpanel-backcolor',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default:
      'var(--sjs-editor-background, var(--sjs-general-backcolor-dim-light, var(--background-dim-light, #f9f9f9)))',
    source: 'variables.scss:13',
  },
  {
    name: '--sjs-editorpanel-cornerRadius',
    class: 'semantic-derived',
    grammar: {
      kind: 'length',
    },
    default: 'var(--sjs-corner-radius, 4px)',
    source: 'variables.scss:30',
  },
  {
    name: '--sjs-editorpanel-hovercolor',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-general-backcolor-dim-dark, rgb(243, 243, 243))',
    source: 'variables.scss:27',
  },
  {
    name: '--sjs-element-fade-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:154',
  },
  {
    name: '--sjs-element-fade-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '500ms',
    source: 'variables.scss:152',
  },
  {
    name: '--sjs-element-fade-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:155',
  },
  {
    name: '--sjs-element-move-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:153',
  },
  {
    name: '--sjs-element-move-out-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '0ms',
    source: 'variables.scss:157',
  },
  {
    name: '--sjs-element-move-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:156',
  },
  {
    name: '--sjs-expand-fade-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:140',
  },
  {
    name: '--sjs-expand-fade-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '500ms',
    source: 'variables.scss:138',
  },
  {
    name: '--sjs-expand-move-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:139',
  },
  {
    name: '--sjs-font-editorfont-color',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-general-forecolor, rgba(0, 0, 0, 0.91))',
    source: 'variables.scss:115',
  },
  {
    name: '--sjs-font-editorfont-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--sjs-font-family, var(--font-family, var(--sjs-default-font-family)))',
    source: 'variables.scss:113',
  },
  {
    name: '--sjs-font-editorfont-placeholdercolor',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default:
      'var(--sjs-general-forecolor-light, var(--foreground-light, #909090))',
    source: 'variables.scss:116',
  },
  {
    name: '--sjs-font-editorfont-size',
    class: 'semantic-derived',
    grammar: {
      kind: 'length',
    },
    default: 'var(--sjs-font-size, 16px)',
    source: 'variables.scss:120',
  },
  {
    name: '--sjs-font-editorfont-weight',
    class: 'semantic-derived',
    grammar: {
      kind: 'fontWeight',
    },
    default: '400',
    source: 'variables.scss:114',
  },
  {
    name: '--sjs-font-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default: 'var(--font-family, var(--sjs-default-font-family))',
    source: 'variables.scss:62',
  },
  {
    name: '--sjs-font-headerdescription-color',
    class: 'context-dependent',
    grammar: {
      kind: 'color',
    },
    default:
      'var(--sjs-font-pagedescription-color, var(--sjs-general-dim-forecolor-light, rgba(0, 0, 0, 0.45)))',
    source: 'variables.scss:79',
    accentDefault:
      'var(--sjs-primary-forecolor, var(--primary-foreground, #fff))',
  },
  {
    name: '--sjs-font-headerdescription-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--sjs-font-family, var(--font-family, var(--sjs-default-font-family)))',
    source: 'variables.scss:77',
  },
  {
    name: '--sjs-font-headerdescription-size',
    class: 'semantic-derived',
    grammar: {
      kind: 'length',
    },
    default: '20px',
    source: 'mixins.scss:206',
  },
  {
    name: '--sjs-font-headerdescription-weight',
    class: 'semantic-derived',
    grammar: {
      kind: 'fontWeight',
    },
    default: '400',
    source: 'variables.scss:78',
  },
  {
    name: '--sjs-font-headertitle-color',
    class: 'context-dependent',
    grammar: {
      kind: 'color',
    },
    default:
      'var(--sjs-font-pagetitle-color, var(--sjs-general-dim-forecolor, rgba(0, 0, 0, 0.91)))',
    source: 'variables.scss:75',
    accentDefault:
      'var(--sjs-primary-forecolor, var(--primary-foreground, #fff))',
  },
  {
    name: '--sjs-font-headertitle-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--sjs-font-family, var(--font-family, var(--sjs-default-font-family)))',
    source: 'variables.scss:73',
  },
  {
    name: '--sjs-font-headertitle-size',
    class: 'semantic-derived',
    grammar: {
      kind: 'calc',
    },
    default: 'calc(2 * (var(--sjs-font-size, 16px)))',
    source: 'mixins.scss:200',
  },
  {
    name: '--sjs-font-headertitle-weight',
    class: 'semantic-derived',
    grammar: {
      kind: 'fontWeight',
    },
    default: '700',
    source: 'variables.scss:74',
  },
  {
    name: '--sjs-font-pagedescription-color',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-general-dim-forecolor-light, rgba(0, 0, 0, 0.45))',
    source: 'variables.scss:87',
  },
  {
    name: '--sjs-font-pagedescription-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--sjs-font-family, var(--font-family, var(--sjs-default-font-family)))',
    source: 'variables.scss:85',
  },
  {
    name: '--sjs-font-pagedescription-size',
    class: 'semantic-derived',
    grammar: {
      kind: 'length',
    },
    default: 'var(--sjs-font-size, 16px)',
    source: 'variables.scss:91',
  },
  {
    name: '--sjs-font-pagedescription-weight',
    class: 'semantic-derived',
    grammar: {
      kind: 'fontWeight',
    },
    default: '400',
    source: 'variables.scss:86',
  },
  {
    name: '--sjs-font-pagetitle-color',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-general-dim-forecolor, rgba(0, 0, 0, 0.91))',
    source: 'variables.scss:83',
  },
  {
    name: '--sjs-font-pagetitle-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--sjs-font-family, var(--font-family, var(--sjs-default-font-family)))',
    source: 'variables.scss:81',
  },
  {
    name: '--sjs-font-pagetitle-size',
    class: 'semantic-derived',
    grammar: {
      kind: 'calc',
    },
    default: 'calc(1.5 * (var(--sjs-font-size, 16px)))',
    source: 'mixins.scss:177',
  },
  {
    name: '--sjs-font-pagetitle-weight',
    class: 'semantic-derived',
    grammar: {
      kind: 'fontWeight',
    },
    default: '700',
    source: 'variables.scss:82',
  },
  {
    name: '--sjs-font-questiondescription-color',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-general-forecolor-light, rgba(0, 0, 0, 0.45))',
    source: 'variables.scss:103',
    alternates: [
      {
        expression:
          'var(--sjs-general-dim-forecolor-light, rgba(0, 0, 0, 0.45))',
        source: 'blocks/sv-ranking.scss:423',
      },
    ],
  },
  {
    name: '--sjs-font-questiondescription-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--sjs-font-family, var(--font-family, var(--sjs-default-font-family)))',
    source: 'variables.scss:101',
  },
  {
    name: '--sjs-font-questiondescription-size',
    class: 'semantic-derived',
    grammar: {
      kind: 'length',
    },
    default: 'var(--sjs-font-size, 16px)',
    source: 'variables.scss:107',
  },
  {
    name: '--sjs-font-questiondescription-weight',
    class: 'semantic-derived',
    grammar: {
      kind: 'fontWeight',
    },
    default: '400',
    source: 'variables.scss:102',
  },
  {
    name: '--sjs-font-questiontitle-color',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-general-forecolor, var(--foreground, #161616))',
    source: 'variables.scss:95',
  },
  {
    name: '--sjs-font-questiontitle-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--sjs-font-family, var(--font-family, var(--sjs-default-font-family)))',
    source: 'variables.scss:93',
  },
  {
    name: '--sjs-font-questiontitle-size',
    class: 'semantic-derived',
    grammar: {
      kind: 'length',
    },
    default: 'var(--sjs-font-size, 16px)',
    source: 'variables.scss:99',
  },
  {
    name: '--sjs-font-questiontitle-weight',
    class: 'semantic-derived',
    grammar: {
      kind: 'fontWeight',
    },
    default: '600',
    source: 'variables.scss:94',
  },
  {
    name: '--sjs-font-size',
    class: 'semantic-derived',
    grammar: {
      kind: 'length',
    },
    default: '16px',
    source: 'variables.scss:63',
  },
  {
    name: '--sjs-font-surveydescription-color',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default:
      'var(--sjs-general-forecolor-light, var(--foreground-light, #909090))',
    source: 'variables.scss:71',
  },
  {
    name: '--sjs-font-surveydescription-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--sjs-font-family, var(--font-family, var(--sjs-default-font-family)))',
    source: 'variables.scss:69',
  },
  {
    name: '--sjs-font-surveydescription-size',
    class: 'semantic-derived',
    grammar: {
      kind: 'length',
    },
    default: 'var(--sjs-font-size, 16px)',
    source: 'mixins.scss:194',
  },
  {
    name: '--sjs-font-surveydescription-weight',
    class: 'semantic-derived',
    grammar: {
      kind: 'fontWeight',
    },
    default: '400',
    source: 'variables.scss:70',
  },
  {
    name: '--sjs-font-surveytitle-color',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-primary-backcolor, var(--primary, #19b394))',
    source: 'variables.scss:67',
  },
  {
    name: '--sjs-font-surveytitle-family',
    class: 'semantic-derived',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--sjs-font-family, var(--font-family, var(--sjs-default-font-family)))',
    source: 'variables.scss:65',
  },
  {
    name: '--sjs-font-surveytitle-size',
    class: 'semantic-derived',
    grammar: {
      kind: 'calc',
    },
    default: 'calc(2 * (var(--sjs-font-size, 16px)))',
    source: 'mixins.scss:188',
  },
  {
    name: '--sjs-font-surveytitle-weight',
    class: 'semantic-derived',
    grammar: {
      kind: 'fontWeight',
    },
    default: '700',
    source: 'variables.scss:66',
  },
  {
    name: '--sjs-general-backcolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--background, #fff)',
    source: 'variables.scss:17',
  },
  {
    name: '--sjs-general-backcolor-dark',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'rgb(248, 248, 248)',
    source: 'variables.scss:26',
  },
  {
    name: '--sjs-general-backcolor-dim',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--background-dim, #f3f3f3)',
    source: 'variables.scss:23',
  },
  {
    name: '--sjs-general-backcolor-dim-dark',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'rgb(243, 243, 243)',
    source: 'variables.scss:27',
    alternates: [
      {
        expression: '#f3f3f3',
        source: 'blocks/sd-dropdown.scss:110',
      },
    ],
  },
  {
    name: '--sjs-general-backcolor-dim-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--background-dim-light, #f9f9f9)',
    source: 'variables.scss:13',
  },
  {
    name: '--sjs-general-dim-forecolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(0, 0, 0, 0.91)',
    source: 'variables.scss:35',
  },
  {
    name: '--sjs-general-dim-forecolor-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(0, 0, 0, 0.45)',
    source: 'variables.scss:36',
  },
  {
    name: '--sjs-general-forecolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--foreground, #161616)',
    source: 'variables.scss:33',
  },
  {
    name: '--sjs-general-forecolor-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--foreground-light, #909090)',
    source: 'variables.scss:34',
  },
  {
    name: '--sjs-header-backcolor',
    class: 'context-dependent',
    grammar: {
      kind: 'color',
    },
    default: 'transparent',
    source: 'blocks/header.scss:6',
    accentDefault: 'var(--sjs-primary-backcolor, var(--primary, #19b394))',
  },
  {
    name: '--sjs-list-item-level',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: null,
    source: 'blocks/sv-list.scss:55',
  },
  {
    name: '--sjs-list-item-padding-left',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default:
      'calc(var(--sjs-list-item-level) * var(--sjs-list-item-padding-left-default))',
    source: 'blocks/sv-list.scss:55',
    alternates: [
      {
        expression: 'calcSize(2)',
        source: 'blocks/sv-list.scss:64',
      },
    ],
  },
  {
    name: '--sjs-list-item-padding-left-default',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: 'calc(2 * var(--sjs-base-unit, var(--base-unit, 8px)))',
    source: 'blocks/sv-list.scss:54',
  },
  {
    name: '--sjs-matrix-detail-row-fade-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:168',
  },
  {
    name: '--sjs-matrix-detail-row-fade-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '500ms',
    source: 'variables.scss:166',
  },
  {
    name: '--sjs-matrix-detail-row-fade-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:169',
  },
  {
    name: '--sjs-matrix-detail-row-move-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:167',
  },
  {
    name: '--sjs-matrix-detail-row-move-out-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:171',
  },
  {
    name: '--sjs-matrix-detail-row-move-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:170',
  },
  {
    name: '--sjs-matrix-row-fade-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:161',
  },
  {
    name: '--sjs-matrix-row-fade-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:159',
  },
  {
    name: '--sjs-matrix-row-fade-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:162',
  },
  {
    name: '--sjs-matrix-row-move-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:160',
  },
  {
    name: '--sjs-matrix-row-move-out-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:164',
  },
  {
    name: '--sjs-matrix-row-move-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:163',
  },
  {
    name: '--sjs-pd-list-fade-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:195',
  },
  {
    name: '--sjs-pd-list-fade-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '500ms',
    source: 'variables.scss:193',
  },
  {
    name: '--sjs-pd-list-fade-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:196',
  },
  {
    name: '--sjs-pd-list-move-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:194',
  },
  {
    name: '--sjs-pd-list-move-out-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:198',
  },
  {
    name: '--sjs-pd-list-move-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:197',
  },
  {
    name: '--sjs-pd-tab-add-fade-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:188',
  },
  {
    name: '--sjs-pd-tab-add-fade-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '500ms',
    source: 'variables.scss:187',
  },
  {
    name: '--sjs-pd-tab-animation-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '0ms',
    source: 'blocks/sd-paneldynamic.scss:342',
    alternates: [
      {
        expression: 'var(--sjs-pd-tab-remove-fade-in-delay, 150ms)',
        source: 'blocks/sd-paneldynamic.scss:396',
      },
    ],
  },
  {
    name: '--sjs-pd-tab-fade-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:178',
  },
  {
    name: '--sjs-pd-tab-fade-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:177',
  },
  {
    name: '--sjs-pd-tab-fade-out-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '0ms',
    source: 'variables.scss:180',
  },
  {
    name: '--sjs-pd-tab-fade-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:179',
  },
  {
    name: '--sjs-pd-tab-height-change-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '0ms',
    source: 'variables.scss:174',
  },
  {
    name: '--sjs-pd-tab-height-change-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:173',
  },
  {
    name: '--sjs-pd-tab-move-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:176',
  },
  {
    name: '--sjs-pd-tab-move-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:175',
  },
  {
    name: '--sjs-pd-tab-move-in-margin',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '50%',
    source: 'variables.scss:183',
  },
  {
    name: '--sjs-pd-tab-move-margin',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: 'calc(1 * var(--sjs-pd-tab-move-in-margin, 50%))',
    source: 'blocks/sd-paneldynamic.scss:360',
    alternates: [
      {
        expression: 'calc(-1 * var(--sjs-pd-tab-move-in-margin, 50%))',
        source: 'blocks/sd-paneldynamic.scss:363',
      },
      {
        expression: 'calc(-1 * var(--sjs-pd-tab-move-out-margin, 50%))',
        source: 'blocks/sd-paneldynamic.scss:380',
      },
      {
        expression: 'calc(1 * var(--sjs-pd-tab-move-out-margin, 50%))',
        source: 'blocks/sd-paneldynamic.scss:383',
      },
    ],
  },
  {
    name: '--sjs-pd-tab-move-out-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '0ms',
    source: 'variables.scss:182',
  },
  {
    name: '--sjs-pd-tab-move-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:181',
  },
  {
    name: '--sjs-pd-tab-move-out-margin',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '50%',
    source: 'variables.scss:184',
  },
  {
    name: '--sjs-pd-tab-remove-fade-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:191',
  },
  {
    name: '--sjs-pd-tab-remove-fade-out-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '0ms',
    source: 'variables.scss:190',
  },
  {
    name: '--sjs-pd-tab-remove-fade-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:189',
  },
  {
    name: '--sjs-postcss-fix-slider-path-color',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: 'var(--lbr-slider-path-color)',
    source: 'blocks/sd-slider.scss:5',
    alternates: [
      {
        expression: 'var(--sjs-border-light, var(--border-light, #eaeaea))',
        source: 'blocks/sd-slider.scss:73',
      },
    ],
  },
  {
    name: '--sjs-postcss-fix-slider-path-color-filled',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: 'var(--lbr-slider-path-color-filled)',
    source: 'blocks/sd-slider.scss:6',
    alternates: [
      {
        expression: 'var(--sjs-primary-backcolor, var(--primary, #19b394))',
        source: 'blocks/sd-slider.scss:104',
      },
    ],
  },
  {
    name: '--sjs-postcss-fix-slider-path-height',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--lbr-slider-path-height, calc(0.5 * (var(--sjs-base-unit, var(--base-unit, 8px)))))',
    source: 'blocks/sd-slider.scss:4',
  },
  {
    name: '--sjs-postcss-fix-slider-path-height-preview',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--lbr-slider-path-height-preview, calc(0.125 * (var(--sjs-base-unit, var(--base-unit, 8px)))))',
    source: 'blocks/sd-slider.scss:12',
  },
  {
    name: '--sjs-postcss-fix-slider-thumb-color',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--lbr-slider-thumb-color, var(--sjs-questionpanel-backcolor, var(--sjs-question-background, var(--sjs-general-backcolor, var(--background, #fff)))))',
    source: 'blocks/sd-slider.scss:9',
  },
  {
    name: '--sjs-postcss-fix-slider-thumb-height',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--lbr-slider-thumb-height, calc(4 * (var(--sjs-base-unit, var(--base-unit, 8px)))))',
    source: 'blocks/sd-slider.scss:8',
  },
  {
    name: '--sjs-postcss-fix-slider-thumb-width',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--lbr-slider-thumb-width, calc(4 * (var(--sjs-base-unit, var(--base-unit, 8px)))))',
    source: 'blocks/sd-slider.scss:7',
  },
  {
    name: '--sjs-postcss-fix-slider-tooltip-pointer-height',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--lbr-tooltip-pointer-height, calc(0.75 * (var(--sjs-base-unit, var(--base-unit, 8px)))))',
    source: 'blocks/sd-slider.scss:11',
  },
  {
    name: '--sjs-postcss-fix-slider-tooltip-pointer-width',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default:
      'var(--lbr-tooltip-pointer-width, calc(1.5 * (var(--sjs-base-unit, var(--base-unit, 8px)))))',
    source: 'blocks/sd-slider.scss:10',
  },
  {
    name: '--sjs-primary-backcolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--primary, #19b394)',
    source: 'variables.scss:1',
    alternates: [
      {
        expression: '#ff00ff',
        source: 'blocks/sd-imagemap.scss:30',
      },
    ],
  },
  {
    name: '--sjs-primary-backcolor-dark',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'rgb(20, 164, 139)',
    source: 'variables.scss:3',
  },
  {
    name: '--sjs-primary-backcolor-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--primary-light, rgba(25, 179, 148, 0.1))',
    source: 'variables.scss:2',
    alternates: [
      {
        expression: '#ff00ff',
        source: 'blocks/sd-imagemap.scss:29',
      },
    ],
  },
  {
    name: '--sjs-primary-forecolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--primary-foreground, #fff)',
    source: 'variables.scss:4',
  },
  {
    name: '--sjs-primary-forecolor-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--primary-foreground-disabled, rgba(255, 255, 255, 0.25))',
    source: 'variables.scss:5',
  },
  {
    name: '--sjs-question-background',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-general-backcolor, var(--background, #fff))',
    source: 'variables.scss:17',
  },
  {
    name: '--sjs-questionpanel-backcolor',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default:
      'var(--sjs-question-background, var(--sjs-general-backcolor, var(--background, #fff)))',
    source: 'variables.scss:17',
  },
  {
    name: '--sjs-questionpanel-cornerRadius',
    class: 'semantic-derived',
    grammar: {
      kind: 'length',
    },
    default: 'var(--sjs-corner-radius, 4px)',
    source: 'variables.scss:31',
  },
  {
    name: '--sjs-questionpanel-hovercolor',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-general-backcolor-dark, rgb(248, 248, 248))',
    source: 'variables.scss:26',
  },
  {
    name: '--sjs-range-slider-range-input-thumb-left',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '0',
    source: 'blocks/sd-slider.scss:399',
  },
  {
    name: '--sjs-range-slider-range-input-thumb-position',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: 'absolute',
    source: 'blocks/sd-slider.scss:400',
    alternates: [
      {
        expression: 'relative',
        source: 'blocks/sd-slider.scss:412',
      },
    ],
  },
  {
    name: '--sjs-range-slider-range-input-thumb-width',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '0px',
    source: 'blocks/sd-slider.scss:398',
  },
  {
    name: '--sjs-ranking-fade-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:147',
  },
  {
    name: '--sjs-ranking-fade-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:145',
  },
  {
    name: '--sjs-ranking-fade-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:148',
  },
  {
    name: '--sjs-ranking-move-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:146',
  },
  {
    name: '--sjs-ranking-move-out-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '0ms',
    source: 'variables.scss:150',
  },
  {
    name: '--sjs-ranking-move-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:149',
  },
  {
    name: '--sjs-row-fade-in-animation-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '400ms',
    source: 'variables.scss:136',
  },
  {
    name: '--sjs-row-fade-in-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:132',
  },
  {
    name: '--sjs-row-fade-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '500ms',
    source: 'variables.scss:130',
  },
  {
    name: '--sjs-row-fade-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:133',
  },
  {
    name: '--sjs-row-move-in-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:131',
  },
  {
    name: '--sjs-row-move-out-delay',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '100ms',
    source: 'variables.scss:135',
  },
  {
    name: '--sjs-row-move-out-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '250ms',
    source: 'variables.scss:134',
  },
  {
    name: '--sjs-secondary-backcolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--secondary, #ff9814)',
    source: 'variables.scss:7',
    alternates: [
      {
        expression: '#ff00ff',
        source: 'blocks/sd-imagemap.scss:25',
      },
    ],
  },
  {
    name: '--sjs-secondary-backcolor-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--secondary-light, rgba(255, 152, 20, 0.25))',
    source: 'variables.scss:8',
    alternates: [
      {
        expression: '#ff00ff',
        source: 'blocks/sd-imagemap.scss:24',
      },
    ],
  },
  {
    name: '--sjs-secondary-backcolor-semi-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(255, 152, 20, 0.1)',
    source: 'variables.scss:9',
  },
  {
    name: '--sjs-secondary-forecolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: '#fff',
    source: 'variables.scss:10',
  },
  {
    name: '--sjs-secondary-forecolor-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(255, 255, 255, 0.25)',
    source: 'variables.scss:11',
  },
  {
    name: '--sjs-semantic-blue-background-10',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default:
      'var(--sjs-special-blue-light, var(--blue-light, rgba(67, 127, 217, 0.1)))',
    source: 'blocks/sd-error.scss:35',
  },
  {
    name: '--sjs-semantic-blue-background-500',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-special-blue, #437fd9)',
    source: 'blocks/sd-error.scss:37',
  },
  {
    name: '--sjs-semantic-yellow-background-10',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default:
      'var(--sjs-special-yellow-light, var(--yellow-light, rgba(255, 152, 20, 0.1)))',
    source: 'blocks/sd-error.scss:27',
  },
  {
    name: '--sjs-semantic-yellow-background-500',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: 'var(--sjs-secondary-backcolor, var(--secondary, #ff9814))',
    source: 'blocks/sd-error.scss:30',
  },
  {
    name: '--sjs-shadow-inner',
    class: 'preset-base',
    grammar: {
      kind: 'shadow',
    },
    default: 'inset 0px 1px 2px 0px rgba(0, 0, 0, 0.15)',
    source: 'variables.scss:46',
  },
  {
    name: '--sjs-shadow-inner-reset',
    class: 'preset-base',
    grammar: {
      kind: 'shadow',
    },
    default: 'inset 0px 0px 0px 0px rgba(0, 0, 0, 0.15)',
    source: 'variables.scss:47',
  },
  {
    name: '--sjs-shadow-large',
    class: 'preset-base',
    grammar: {
      kind: 'shadow',
    },
    default: '0px 8px 16px 0px rgba(0, 0, 0, 0.1)',
    source: 'variables.scss:45',
  },
  {
    name: '--sjs-shadow-medium',
    class: 'preset-base',
    grammar: {
      kind: 'shadow',
    },
    default: '0px 2px 6px 0px rgba(0, 0, 0, 0.1)',
    source: 'variables.scss:44',
  },
  {
    name: '--sjs-shadow-small',
    class: 'preset-base',
    grammar: {
      kind: 'shadow',
    },
    default: '0px 1px 2px 0px rgba(0, 0, 0, 0.15)',
    source: 'variables.scss:42',
  },
  {
    name: '--sjs-shadow-small-reset',
    class: 'preset-base',
    grammar: {
      kind: 'shadow',
    },
    default: '0px 0px 0px 0px rgba(0, 0, 0, 0.15)',
    source: 'variables.scss:43',
  },
  {
    name: '--sjs-special-blue',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: '#437fd9',
    source: 'variables.scss:58',
  },
  {
    name: '--sjs-special-blue-forecolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: '#ffffff',
    source: 'variables.scss:60',
  },
  {
    name: '--sjs-special-blue-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--blue-light, rgba(67, 127, 217, 0.1))',
    source: 'variables.scss:59',
  },
  {
    name: '--sjs-special-glow',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: '#004c441a',
    source: 'blocks/sd-slider.scss:218',
  },
  {
    name: '--sjs-special-green',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--green, #19b394)',
    source: 'variables.scss:55',
  },
  {
    name: '--sjs-special-green-forecolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: '#ffffff',
    source: 'variables.scss:57',
  },
  {
    name: '--sjs-special-green-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--green-light, rgba(25, 179, 148, 0.1))',
    source: 'variables.scss:56',
  },
  {
    name: '--sjs-special-red',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--red, #e60a3e)',
    source: 'variables.scss:49',
    alternates: [
      {
        expression: '#E50A3E',
        source: 'blocks/sv-popup.scss:312',
      },
    ],
  },
  {
    name: '--sjs-special-red-forecolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: '#ffffff',
    source: 'variables.scss:51',
  },
  {
    name: '--sjs-special-red-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--red-light, rgba(230, 10, 62, 0.1))',
    source: 'variables.scss:50',
    alternates: [
      {
        expression: 'rgba(229, 10, 62, 0.1)',
        source: 'blocks/sv-popup.scss:309',
      },
    ],
  },
  {
    name: '--sjs-special-shadow',
    class: 'semantic-derived',
    grammar: {
      kind: 'color',
    },
    default: '#00000040',
    source: 'blocks/sd-slider.scss:221',
  },
  {
    name: '--sjs-special-yellow',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--yellow, #ff9814)',
    source: 'variables.scss:52',
  },
  {
    name: '--sjs-special-yellow-forecolor',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: '#ffffff',
    source: 'variables.scss:54',
  },
  {
    name: '--sjs-special-yellow-light',
    class: 'preset-base',
    grammar: {
      kind: 'color',
    },
    default: 'var(--yellow-light, rgba(255, 152, 20, 0.1))',
    source: 'variables.scss:53',
  },
  {
    name: '--sjs-transition-duration',
    class: 'web-only',
    grammar: {
      kind: 'string',
    },
    default: '150ms',
    source: 'variables.scss:127',
  },
  {
    name: '--yellow',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: '#ff9814',
    source: 'derived:--sjs-special-yellow:52',
  },
  {
    name: '--yellow-light',
    class: 'legacy-alias',
    grammar: {
      kind: 'color',
    },
    default: 'rgba(255, 152, 20, 0.1)',
    source: 'derived:--sjs-special-yellow-light:53',
  },
];

/**
 * Explicit review rationale for every non-web-only, non-context-dependent
 * name whose fixture occurrences carry MORE THAN ONE distinct fallback
 * expression (codex review major 4) — enforced exhaustively by
 * __tests__/registry-vs-fixture.test.ts.
 */
export const MULTI_DEFAULT_JUSTIFICATIONS: Readonly<Record<string, string>> = {
  '--sjs-border-default':
    'variables.scss (or the first-declared) default is canonical for token resolution; the divergent per-consumer fallback(s) are component-local styling choices that 0.7 style recipes evaluate per consumer via the exposed alternates.',
  '--sjs-font-questiondescription-color':
    'variables.scss (or the first-declared) default is canonical for token resolution; the divergent per-consumer fallback(s) are component-local styling choices that 0.7 style recipes evaluate per consumer via the exposed alternates.',
  '--sjs-general-backcolor-dim-dark':
    'variables.scss (or the first-declared) default is canonical for token resolution; the divergent per-consumer fallback(s) are component-local styling choices that 0.7 style recipes evaluate per consumer via the exposed alternates.',
  '--sjs-primary-backcolor':
    'variables.scss (or the first-declared) default is canonical for token resolution; the divergent per-consumer fallback(s) are component-local styling choices that 0.7 style recipes evaluate per consumer via the exposed alternates.',
  '--sjs-primary-backcolor-light':
    'variables.scss (or the first-declared) default is canonical for token resolution; the divergent per-consumer fallback(s) are component-local styling choices that 0.7 style recipes evaluate per consumer via the exposed alternates.',
  '--sjs-secondary-backcolor':
    'variables.scss (or the first-declared) default is canonical for token resolution; the divergent per-consumer fallback(s) are component-local styling choices that 0.7 style recipes evaluate per consumer via the exposed alternates.',
  '--sjs-secondary-backcolor-light':
    'variables.scss (or the first-declared) default is canonical for token resolution; the divergent per-consumer fallback(s) are component-local styling choices that 0.7 style recipes evaluate per consumer via the exposed alternates.',
  '--sjs-special-red':
    'variables.scss (or the first-declared) default is canonical for token resolution; the divergent per-consumer fallback(s) are component-local styling choices that 0.7 style recipes evaluate per consumer via the exposed alternates.',
  '--sjs-special-red-light':
    'variables.scss (or the first-declared) default is canonical for token resolution; the divergent per-consumer fallback(s) are component-local styling choices that 0.7 style recipes evaluate per consumer via the exposed alternates.',
};
